name: nebourpos
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.9.1
  printing: ^5.13.4
  pdf: ^3.10.7
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.0
  device_info_plus: ^10.1.0
  package_info_plus: ^9.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  image_path: "assets/icon/icon.png" # ðŸ‘ˆ your main square logo (1024Ã—1024 preferred)
  windows:
    generate: true
    icon_size: 256
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/
    - assets/nebour-logo-dark.png
    - assets/nebour-logo-light.png
